- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Copying proxy file
  ansible.builtin.copy:
    src: proxy.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Clenup
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent 

- name: Create html directory
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: directory

- name: Download and Extracts {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://expense-web-app.s3.amazonaws.com/{{COMPONENT}}.zip
    dest: "{{APP_PATH}}"
    remote_src: yes

- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true

